# Analysis functions to execute on each recording session.
# Key must be a function in src.analysis.analysis_funcs
functions:
  null_percentage:
    columns:
      - 'td_key0'
      - 'td_key2'
      - 'td_key3'
      
  recording_time:
    time_col: 'localTime'

# Criteria to determine if multiple recordings should be aggregated into a single group.
# Must be a function in src.analysis.aggregation_criteria
# E.g. recordings started within a time delta of each other.
aggregation_criteria: # Can be empty or Null if no aggregation is desired.
  function_name: # The first argument of the function session tables, and the second a list of the analysis_pipe outputs for each session, and the rest are keyword arguments for the criteria function.
    kwarg1: value1
    kwarg2: value2

